server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_service_db
    username: postgres
    password: postgres

app:
  base-url: http://blog.example.com

services:
  interaction-service:
    url: http://interaction-service:8086
