server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog_service_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:your_local_postgres_password}

services:
  file-service:
    url: http://localhost:8083
  user-service:
    url: http://localhost:8081

file:
  service:
    url: http://localhost:8083
