server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://file-db:5432/file_service_db
    username: postgres
    password: postgres

seaweedfs:
  master:
    url: http://seaweedfs-master:9333
  filer:
    url: http://seaweedfs-filer:8888
