apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: REPLACE_ME
  SPRING_MAIL_USERNAME: REPLACE_ME
  SPRING_MAIL_PASSWORD: REPLACE_ME
  AI_API_KEY: REPLACE_ME
