apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
      - name: seaweedfs-volume
        image: chrislusf/seaweedfs:latest
        args:
          - volume
          - -dir=/data
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: seaweedfs-volume-pvc
